# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LensCalcPy',
                'doc_host': 'https://NolanSmyth.github.io',
                'git_url': 'https://github.com/NolanSmyth/LensCalcPy',
                'lib_path': 'LensCalcPy'},
  'syms': {'LensCalcPy.core': {'LensCalcPy.core.foo': ('core.html#foo', 'LensCalcPy/core.py')}}}
