# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LensCalcPy',
                'doc_host': 'https://NolanSmyth.github.io',
                'git_url': 'https://github.com/NolanSmyth/LensCalcPy',
                'lib_path': 'LensCalcPy'},
  'syms': { 'LensCalcPy.core': {'LensCalcPy.core.foo': ('ffp.html#foo', 'LensCalcPy/core.py')},
            'LensCalcPy.parameters': {},
            'LensCalcPy.pbh': { 'LensCalcPy.pbh.Pbh': ('pbh.html#pbh', 'LensCalcPy/pbh.py'),
                                'LensCalcPy.pbh.Pbh.__init__': ('pbh.html#pbh.__init__', 'LensCalcPy/pbh.py'),
                                'LensCalcPy.pbh.Pbh.__str__': ('pbh.html#pbh.__str__', 'LensCalcPy/pbh.py'),
                                'LensCalcPy.pbh.Pbh.density': ('pbh.html#pbh.density', 'LensCalcPy/pbh.py')},
            'LensCalcPy.survey': { 'LensCalcPy.survey.Survey': ('survey.html#survey', 'LensCalcPy/survey.py'),
                                   'LensCalcPy.survey.Survey.__init__': ('survey.html#survey.__init__', 'LensCalcPy/survey.py'),
                                   'LensCalcPy.survey.Survey.__str__': ('survey.html#survey.__str__', 'LensCalcPy/survey.py'),
                                   'LensCalcPy.survey.Survey.dist_mw': ('survey.html#survey.dist_mw', 'LensCalcPy/survey.py')}}}
