# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ffp.ipynb.

# %% auto 0
__all__ = ['Ffp', 'get_primed_coords', 'foo']

# %% ../nbs/01_ffp.ipynb 3
from .parameters import *
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import nquad


# %% ../nbs/01_ffp.ipynb 5
class Ffp:
    """A class to represent a FFP population"""

    

# %% ../nbs/01_ffp.ipynb 6
# from below 16 of https://iopscience.iop.org/article/10.3847/1538-4357/ac07a8/pdf*)
# alphabar = 27 Degrees xp-axis is aligned with the major axis
# of the Galactic bar,where \[Alpha]bar=27\[Degree] is applied as the bar angle.
# assuming z ~= 0 and we are looking at line of sight to galactic center from Sun
# galactocentric coordniates x', y' as function of d, distance from Sun

def get_primed_coords(d: float # distance from Sun
                      )-> tuple:
    """Get galactocentric coordinates x', y' as function of d, distance from Sun
    """
    x = rEarth - d
    y = 0
    return (x**2 + y**2)**0.5 * np.cos(alphabar*np.pi/180), (x**2 + y**2)**0.5 * np.sin(alphabar*np.pi/180)

# %% ../nbs/01_ffp.ipynb 23
def foo(): pass
