# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_parameters.ipynb.

# %% auto 0
__all__ = ['rhoc', 'rs', 'G', 'ds', 'c', 'fpbh', 'ut', 'obsTime', 'kpctokm', 'htosec', 'rEarth', 'l', 'b']

# %% ../nbs/05_parameters.ipynb 3
rhoc = 4.88e6 # MW nfw central density parameter in Msol kpc^-3
rs = 21.5 # MW nfw scale radius in kpc
G = 4.3e-6 # kpc Msol^-1 (km/s)^2
ds = 9.0 # kpc
c = 2.98e5 # km/s
fpbh = 1 # fraction of dark matter in PBHs
ut = 1 # threshold impact parameter

obsTime = 7 # observation time in hours
kpctokm = 3e16 # kpc to km
htosec = 60*60 # hours to seconds

rEarth = 8.5 # kpc

l = 1.0 #degrees
b = -1.03 #degrees
